packages:
  - packages/*
  - vscode
  - inspect-extension

catalog:
  '@mpxjs/core': ^2.10.13
  '@types/node': ^22.15.32
  '@types/path-browserify': ^1.0.1
  '@types/semver': ^7.7.0
  '@volar/language-core': ~2.4.12
  '@volar/language-server': ~2.4.12
  '@volar/language-service': ~2.4.12
  '@volar/typescript': ~2.4.12
  '@volar/vscode': ~2.4.12
  '@vue/compiler-dom': ^3.5.0
  path-browserify: ^1.0.1
  reactive-vscode: ^0.2.14
  typescript: ^5.9.2
  vscode-uri: ^3.1.0

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - nx
  - simple-git-hooks

overrides:
  stylus: 0.64.0

peerDependencyRules:
  allowedVersions:
    vue-flow-layout>vue: '2'
