import type * as ts from 'typescript'
import type { RequestContext } from './types'
import { MpxVirtualCode } from '@mpxjs/language-core'
import { getComponentType, getVariableType } from './utils'

export interface ComponentPropInfo {
  name: string
  type?: string
  required?: boolean
  deprecated?: boolean
  isAttribute?: boolean
  commentMarkdown?: string
  values?: string[]
}

type ResolvedComponentPropInfo = ComponentPropInfo & {
  typeParts: string[]
}

export function getComponentProps(
  this: RequestContext,
  fileName: string,
  tag: string,
) {
  const { typescript: ts, language, languageService, getFileId } = this
  const volarFile = language.scripts.get(getFileId(fileName))
  if (!(volarFile?.generated?.root instanceof MpxVirtualCode)) {
    return
  }
  const mpxCode = volarFile.generated.root
  let components: NonNullable<ReturnType<typeof getVariableType>> | undefined
  let componentType: ts.Type | undefined

  // Mpx custom components come from JSON registration. Query its precise map
  // first: __VLS_components also intersects GlobalComponents, which can be
  // `any` in Mpx projects and erase every custom component prop.
  for (const variableName of ['__MPX_jsonComponents', '__VLS_components']) {
    const candidateComponents = getVariableType(
      ts,
      languageService,
      mpxCode,
      variableName,
    )
    if (!candidateComponents) {
      continue
    }
    const candidateType = getComponentType(
      ts,
      languageService,
      mpxCode,
      candidateComponents,
      fileName,
      tag,
    )
    if (candidateType) {
      components = candidateComponents
      componentType = candidateType
      break
    }
  }

  if (!components || !componentType) {
    return []
  }

  const program = languageService.getProgram()!
  const checker = program.getTypeChecker()

  const propsTypes = getComponentPropsTypes(
    checker,
    componentType,
    components.node,
  )
  const candidates = propsTypes.map(propsType => {
    const props = new Map<string, ResolvedComponentPropInfo>()
    for (const prop of propsType.getProperties()) {
      const info = getPropInfo(ts, checker, prop, components.node)
      if (info) {
        props.set(info.name, info)
      }
    }
    return props
  })

  return mergeCandidateProps(candidates)
}

/**
 * Mpx components generated by language-core expose their public props through
 * `new (props: PublicProps)`. Prefer that Mpx-specific contract and retain the
 * Vue-compatible `$props` / call-signature paths only as fallbacks for global
 * components supplied by third-party libraries.
 */
function getComponentPropsTypes(
  checker: ts.TypeChecker,
  componentType: ts.Type,
  location: ts.Node,
) {
  const result = new Set<ts.Type>()

  for (const candidate of flattenUnion(componentType)) {
    const constructSignatures = candidate.getConstructSignatures()
    for (const signature of constructSignatures) {
      const propsParam = signature.parameters[0]
      if (propsParam) {
        addPropsType(checker.getTypeOfSymbolAtLocation(propsParam, location))
        continue
      }

      const propsSymbol = signature.getReturnType().getProperty('$props')
      if (propsSymbol) {
        addPropsType(checker.getTypeOfSymbolAtLocation(propsSymbol, location))
      }
    }

    if (!constructSignatures.length) {
      for (const signature of candidate.getCallSignatures()) {
        const propsParam = signature.parameters[0]
        if (propsParam) {
          addPropsType(checker.getTypeOfSymbolAtLocation(propsParam, location))
        }
      }
    }
  }

  return [...result]

  function addPropsType(type: ts.Type) {
    for (const candidate of flattenUnion(type)) {
      result.add(candidate)
    }
  }
}

function flattenUnion(type: ts.Type): ts.Type[] {
  return type.isUnion() ? type.types.flatMap(flattenUnion) : [type]
}

function getPropInfo(
  ts: typeof import('typescript'),
  checker: ts.TypeChecker,
  prop: ts.Symbol,
  fallbackLocation: ts.Node,
): ResolvedComponentPropInfo | undefined {
  if (prop.flags & ts.SymbolFlags.Method) {
    return
  }

  const location =
    prop.valueDeclaration ?? prop.declarations?.[0] ?? fallbackLocation
  const propType = checker.getTypeOfSymbolAtLocation(prop, location)
  const typeParts = flattenUnion(propType).map(type =>
    checker.typeToString(type, location, ts.TypeFormatFlags.NoTruncation),
  )
  const { content: commentMarkdown, deprecated } = generateCommentMarkdown(
    prop.getDocumentationComment(checker),
    prop.getJsDocTags(),
  )
  const values = flattenUnion(propType)
    .filter(
      type =>
        type.isStringLiteral() ||
        type.isNumberLiteral() ||
        (type.flags & ts.TypeFlags.BooleanLiteral) !== 0,
    )
    .map(type =>
      type.isStringLiteral()
        ? type.value
        : type.isNumberLiteral()
          ? String(type.value)
          : checker.typeToString(type, location),
    )

  let isAttribute: boolean | undefined
  for (const { parent } of checker
    .getRootSymbols(prop)
    .flatMap(root => root.declarations ?? [])) {
    if (!ts.isInterfaceDeclaration(parent)) {
      continue
    }
    const { text } = parent.name
    if (
      text.endsWith('HTMLAttributes') ||
      text === 'AriaAttributes' ||
      text === 'SVGAttributes'
    ) {
      isAttribute = true
      break
    }
  }

  return {
    name: prop.name,
    type: typeParts.join(' | '),
    typeParts,
    required: !(prop.flags & ts.SymbolFlags.Optional) || undefined,
    deprecated,
    isAttribute,
    commentMarkdown,
    values,
  }
}

function mergeCandidateProps(
  candidates: Map<string, ResolvedComponentPropInfo>[],
): ComponentPropInfo[] {
  const result = new Map<
    string,
    {
      definitions: number
      required: number
      deprecated: number
      isAttribute: boolean
      types: Set<string>
      comments: Set<string>
      values: Set<string>
    }
  >()

  for (const candidate of candidates) {
    for (const prop of candidate.values()) {
      let merged = result.get(prop.name)
      if (!merged) {
        merged = {
          definitions: 0,
          required: 0,
          deprecated: 0,
          isAttribute: false,
          types: new Set(),
          comments: new Set(),
          values: new Set(),
        }
        result.set(prop.name, merged)
      }
      merged.definitions++
      merged.required += prop.required ? 1 : 0
      merged.deprecated += prop.deprecated ? 1 : 0
      merged.isAttribute ||= !!prop.isAttribute
      for (const type of prop.typeParts) {
        merged.types.add(type)
      }
      if (prop.commentMarkdown) {
        merged.comments.add(prop.commentMarkdown)
      }
      for (const value of prop.values ?? []) {
        merged.values.add(value)
      }
    }
  }

  return [...result].map(([name, prop]) => {
    const types = [...prop.types]
    const undefinedIndex = types.indexOf('undefined')
    if (undefinedIndex >= 0) {
      types.push(...types.splice(undefinedIndex, 1))
    }

    return {
      name,
      type: types.join(' | ') || undefined,
      // A prop is required for the union only when every candidate requires it.
      required:
        candidates.length > 0 && prop.required === candidates.length
          ? true
          : undefined,
      deprecated:
        prop.definitions > 0 && prop.deprecated === prop.definitions
          ? true
          : undefined,
      isAttribute: prop.isAttribute || undefined,
      commentMarkdown: [...prop.comments].join('\n\n---\n\n') || undefined,
      values: [...prop.values],
    }
  })
}

function generateCommentMarkdown(
  parts: ts.SymbolDisplayPart[],
  jsDocTags: ts.JSDocTagInfo[],
) {
  const parsedComment = _symbolDisplayPartsToMarkdown(parts)
  const parsedJsDoc = _jsDocTagInfoToMarkdown(jsDocTags)
  const content = [parsedComment, parsedJsDoc].filter(str => !!str).join('\n\n')
  const deprecated = jsDocTags.some(tag => tag.name === 'deprecated')
  return {
    content,
    deprecated,
  }
}

function _symbolDisplayPartsToMarkdown(parts: ts.SymbolDisplayPart[]) {
  return parts
    .map(part => {
      switch (part.kind) {
        case 'keyword':
          return `\`${part.text}\``
        case 'functionName':
          return `**${part.text}**`
        default:
          return part.text
      }
    })
    .join('')
}

function _jsDocTagInfoToMarkdown(jsDocTags: ts.JSDocTagInfo[]) {
  return jsDocTags
    .map(tag => {
      const tagName = `*@${tag.name}*`
      const tagText =
        tag.text
          ?.map(t => {
            if (t.kind === 'parameterName') {
              return `\`${t.text}\``
            } else {
              return t.text
            }
          })
          .join('') || ''

      return `${tagName} ${tagText}`
    })
    .join('\n\n')
}
